[package]
name = "cymbal"
version = "0.3.1"
edition = "2024"
description = "search for symbols in a codebase"
license = "CC0-1.0"
repository = "https://github.com/enricozb/cymbal"
readme = "../readme.md"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
crossbeam = "0.8.4"
extend = "1.2.0"
parking_lot = "0.12.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
streaming-iterator = "0.1.9"
toml = "0.8.20"
tree-sitter = "0.25.3"
tree-sitter-c = "0.23.4"
tree-sitter-cpp = "0.23.4"
tree-sitter-fish = { git = "https://github.com/ram02z/tree-sitter-fish", version = "3.5.1" }
tree-sitter-go = "0.23.4"
tree-sitter-haskell = "0.23.1"
tree-sitter-odin = "1.3.0"
tree-sitter-python = "0.23.6"
tree-sitter-rust = "0.24.0"
tree-sitter-typescript = "0.23.2"
